
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: sote-kube
spec:
  deletionPolicy: "Delete"  
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 3
        vmSize: "Standard_D2s_v3"
        osSku: Ubuntu
        tags:
          environment: "test"
    location: "East US"
    dnsPrefix: "sote"
    resourceGroupName: sotewa-rg   
    identity:
      - type: SystemAssigned
 



